### ISSUE TITLE
Swath Boundary Values

### ISSUE THREAD

**Issue by arminfarshbaf** [gmtsar/gmtsar#116]
I have applied SBAS for three adjacent swaths but for some reason, the middle swath's values differ from the other two, I'm not sure why this happens and would like to know if you guys have any clue. Since the number of interferograms is quite a lot I can't merge them before running SBAS, so I resorted to doing it for each swath individually and merging them in ArcMap afterward.
Thanks in advance
![SS](https://user-images.githubusercontent.com/59362927/112712349-95b49d00-8eec-11eb-9842-ae029f90a890.PNG)

**Comment by dsandwell** [comment]
Hi,

The phase unwrapping program snaphu has a 2 pi integer ambiguity.  So the outer to swaths may unwrap close to zero and the inner swath close to 2 pi or 4 pi.  It is best to merge the swaths before unwrapping so they all have the same ambiguity.  Then  you can filter and downsample to get the interferograms to fit into the memory of the computer or use a computer with more memory.

To rescue this analysis you could look at each interferogram and add or subtract 2 pi from onw or two of the subswaths to make them all have the same ambiguity.  Then the SBAS should be the same although there will probably be slight differences due to the least squares.  

David

> On Mar 26, 2021, at 11:43 PM, arminfarshbaf ***@***.***> wrote:
> 
> 
> I have applied SBAS for three adjacent swaths but for some reason, the middle swath's values differ from the other two, I'm not sure why this happens and would like to know if you guys have any clue. Since the number of interferograms is quite a lot I can't merge them before running SBAS, so I resorted to doing it for each swath individually and merging them in ArcMap afterward.
> Thanks in advance
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by arminfarshbaf** [comment]
Hi David
Thanks for your reply. I took your advice and merged and downsampled the interferograms before unwrapping them which fixed the problem. However, I was wondering what would happen if in another analysis only the middle swath was needed? Would the end results in that scenario be wrong?

**Comment by dsandwell** [comment]
Hi,

Glad that worked out.  OK there is a fundamental issue here.  Every interferogram has an unknown N2pi ambiguity plus some atmospheric error.  There are two approaches to getting a sensible result.

1) Find a point in your area where you think there is no deformation AND no atmospheric error. Calculate the average phase of each interferogram in this area and subtract from each interferogram.  When you do the SBAS, that area will have zero deformation.  The problem with this is that area may have anomalous atmosphere.

2) If you have any GPS in the region, calculate the line of sight GPS deformation between the two times of the interferogram and force each interferogram to match that GPS to within some uncertainty related to your expected GPS and/or atmospheric error.

Both approaches are commonly used in InSAR time series.

Cheers,

David




> On Apr 4, 2021, at 5:28 AM, arminfarshbaf ***@***.***> wrote:
> 
> 
> Hi David
> Thanks for your reply. I took your advice and merged and downsampled the interferograms before unwrapping them which fixed the problem. However, I was wondering what would happen if in another analysis only the middle swath was needed? Would the end results in that scenario be wrong?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by arminfarshbaf** [comment]
Thanks for the comments David, I think I get the gist of it now.
