### ISSUE TITLE
[Help]: solid earth tide correction 

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#203]
I’m reading the document https://topex.ucsd.edu/sandwell/publications/182_TGRS_Xu_Ambiguity.pd and the correction looks equal to just using corrected DEM for each image. We’d calculate the solid earth tide for every DEM pixel and use the corrected DEM. Could you explain why more complex approach is used?

Note: GMTSAR solid earth tide calculation utility includes outdated “temporary new cut-off date until 2020jun30”.

**Comment by dsandwell** [comment]
The tide changes for every acquisition so it cannot be applied to the topography.  Also the tide maps directly into phase like any surface deformation while the topography correction changes with InSAR baseline.  The code must be updated periodically because of unpredictable leap seconds.  

> On Aug 28, 2021, at 9:14 AM, Alexey Pechnikov ***@***.***> wrote:
> 
> 
> I’m reading the document https://topex.ucsd.edu/sandwell/publications/182_TGRS_Xu_Ambiguity.pd and the correction looks equal to just using corrected DEM for each image. We’d calculate the solid earth tide for every DEM pixel and use the corrected DEM. Could you explain why more complex approach is used?
> 
> Note: GMTSAR solid earth tide calculation utility includes outdated “temporary new cut-off date until 2020jun30”.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by mobigroup** [comment]
Yes, it will be a separate topography file for every image. We can generate the corrected topography value to the coordinate and time when the radar scans the point. The phase delta can be defined by distances delta to the topography for a pair of images.
