### ISSUE TITLE
Coregistration Stacking 

### ISSUE THREAD

**Issue by simonst7** [gmtsar/gmtsar#23]
Hi dear all, 
I have a question about the coregistration in the alignment process to Envisat SLC stacking. I follow the alignment with modified align_ALOS_SLC.csh in xcorr parameters, and its working with a secondary alignment slave and supermaster, then I followed intf_tops.csh, with a set the interferograms in intf.in. Then i get the interferograms in folder intf_all, but the results i don't know if they are correct. I compare with the interferogram in the same dates but only one process (p2p_processing ENVI_SLC), with same parameters but that is different wrapped and unwrapped phase. Why i get different results? i think the alignment secondary is different but it's the correct step for the SBAS method or i can follow the SBAS with interferograms made in individual process (p2p_processing). Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Hi simonst7,
First, sorry for getting back so late. Somehow I missed this email. 
I believe it is because the new p2p_processing.csh simply resamples the SLC for co-registration. This should be fine with focusing done at 0 doppler, but for most older satellite, when running align.csh it is focused at non-zero doppler. This is probably the reason causing different phase. I would recommend the former methods as re-focusing at non-zero doppler theoretically should provide better quality images.
Cheers,
Xiaohua(Eric)
