### ISSUE TITLE
[BUG]: SBAS results are not correct

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#234]
For the example S1A_Stack_CPGF_T173 I've selected only valid interferograms without atmosphere disturbances using triplets analysis (see PyGMTSAR codes):
<img width="995" alt="image" src="https://user-images.githubusercontent.com/7342379/135965114-05ed1624-2d6e-4d5c-bf17-6dda282d3031.png">

This is the triplets analysis table and plot:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7342379/135965186-883a58e3-5e8e-4c4a-8baf-d44a4e8689c5.png">
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7342379/135965368-52f33680-0756-4c76-8d77-51c5346585d5.png">

There are no false high coherences and phase differences in the selected interferograms. As I've found, we don't need to fix phase differences but to removed the interferograms because phase differences are related to atmosphere disturbances here as proved above. Ok, we are suppose to obtain ideal SBAS results using the clear interferograms. 

The generated intf.tab table doesn't include interferograms with 2015-04-27:
```
print (sbas.intftab(pairs_valid))

20150121_20150310_unwrap.grd 20150121_20150310_corr.grd 20150121 20150310 -90.33
20150121_20150403_unwrap.grd 20150121_20150403_corr.grd 20150121 20150403 -52.61
20150310_20150403_unwrap.grd 20150310_20150403_corr.grd 20150310 20150403 37.72
20150310_20150521_unwrap.grd 20150310_20150521_corr.grd 20150310 20150521 -13.25
20150403_20150521_unwrap.grd 20150403_20150521_corr.grd 20150403 20150521 -50.97
```

Call SBAS command line tool in debug mode and without soothing and atmosphere correction arguments:

```
sbas.sbas(pairs_valid, debug=True)

sbas /dev/fd/109 /dev/fd/110 5 4 674 685 -smooth 0 -wavelength 0.0554658 -incidence 33.94992694471246 -range 825322.0 -rms -dem
sbas 
compute RMS misfit
compute DEM error

setting smoothing to   0.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  33.950 degree 
setting range to 825322.000 m 
number of SAR scenes is 4 
number of interferograms is 5 

sbas Memory Allocation Successful...
read table file ...
read phase and correlation grids ...
0.000000 0.000492 0.000000 -90.330002
fill the G matrix ...
run least-squares problem over 674 by 685 pixel (0) ...
matrix is rank-deficient: 3

write output ...
```

The output displacements maps are ok and equal to LOS differences calculated directly. Here we see displacement range ~ [-45 mm, 5 mm] for 4 months interval:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/7342379/135966896-6996f661-2650-4b76-a640-fc475dc640c5.png">

But the velocity map is still incorrect:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/7342379/135968590-3124a7e8-2984-41a9-84d9-63e467d8e9d7.png">

That's clear enough when we have displacement range [-45 mm, 5 mm] for 4 month then yearly displacement amplitude should be less than 3*50 mm = 150 mm but SBAS returns amplitude 350 mm (see on the picture above colorbar range [-200 mm, 150 mm]). And positive displacement 150 mm is sure invalid for 5 mm positive displacement in 4 months.

Resume: hard part (atmosphere disturbance estimation) looks ok but easy part (trend calculation) is wrong in the SBAS code.

**Comment by mobigroup** [comment]
You could check on your own example S1A_Stack_CPGF_T173 :) I've found and reported it before and your example produces impossible velocity map too.

**Comment by mobigroup** [comment]
But what are the velocity values? I don't understand why do you sure your result is correct if you don't check the result...

**Comment by mobigroup** [comment]
Thanks, I see the scale on the updated picture. Please attach also the actual values range - minimum and maximum. I suppose the range is much larger than 100...

**Comment by Xiaohua-Eric-Xu** [comment]
Well, you are getting what is expected. The problem is you are treating all these numbers as deformation, while the major component in them is atmospheric noise. 4 acquisition, 5 interferograms, with each containing atm noise that could easily go up to 20cm, what do you expect to resolve? SBAS approach is easy enough to be implemented with some simple scripting. You could easily put noise to simulated data and see how the noise/unwrapping errors affect the solution. 

Berardino, P., Fornaro, G., Lanari, R., & Sansosti, E. (2002). A new algorithm for surface deformation monitoring based on small baseline differential SAR interferograms. IEEE Transactions on geoscience and remote sensing, 40(11), 2375-2383.
Schmidt, D. A., & Bürgmann, R. (2003). Time‐dependent land uplift and subsidence in the Santa Clara valley, California, from a large interferometric synthetic aperture radar data set. Journal of Geophysical Research: Solid Earth, 108(B9).

Beyond that, reading some basics of InSAR may help. 

Simons, M., & Rosen, P. A. (2007). Interferometric synthetic aperture radar geodesy.
Bürgmann, R., Rosen, P. A., & Fielding, E. J. (2000). Synthetic aperture radar interferometry to measure Earth’s surface topography and its deformation. Annual review of earth and planetary sciences, 28(1), 169-209.
Osmanoğlu, B., Sunar, F., Wdowinski, S., & Cabral-Cano, E. (2016). Time series analysis of InSAR data: Methods and trends. ISPRS Journal of Photogrammetry and Remote Sensing, 115, 90-102.

![image](https://user-images.githubusercontent.com/16844111/136436587-87d14829-9843-4670-907f-2cd573675596.png)

**Comment by mobigroup** [comment]
Do you mean SBAS tool generate the atmospheric noice itself? Displacement maps produced by the SBAS tool are reasonable but the velocity map is absolutely different. So the problem is not related to interferograms but to SBAS trend calculation only. I’ve calculated a sum of the  displacements for 4 months above to show that velocity values are much larger for the same interval. Maybe SBAS suppose there are 120 months per year or so on…

**Comment by mobigroup** [comment]
Ok, I could ask even more easy question: how is it possible that for 1 mm displacement per month for 12 month the SBAS tool can return 100 mm/year velocity? I sure there are only 12 months per year and the velocity needs to be less or equal to 12 mm/year for this case!

**Comment by mobigroup** [comment]
Please attach your displacement and velocity grids. I use color scale for the full range and you’ve cropped your scale range that’s only the difference I think.

**Comment by mobigroup** [comment]
Yes, sure, the actual range is much wider than [-20,80] on the picture above:
```
gmt grdinfo vel.grd | grep v_min
vel.grd: v_min: -69.5748062134 v_max: 156.580093384 name: z
```

**Comment by mobigroup** [comment]
We can check for a single pixel. For an example:
```
$ gdallocationinfo -valonly vel.grd 500 500 2>/dev/null
39.443717956543

$ find . -name 'disp*.grd' -print | xargs -I {} gdallocationinfo -valonly {} 500 500 2>/dev/null
-0
-2.15272736549377
-3.4119246006012
9.80659198760986

$ find . -name 'disp*.grd' -print | xargs -I {} echo {}
./disp_2015092.grd
./disp_2015068.grd
./disp_2015140.grd
./disp_2015116.grd
```

As we see, the SBAS velocity is calculated by just two last points: (9.8- -3.41) * (365/120) = 40,18 ~= 39.44... value in vel.grd. Do you still think that's the right trend?

**Comment by mobigroup** [comment]
Ok, nice, now the regression result looks ok and your velocity values are similar to my results. Thanks, I’ll check the new grids.
