### ISSUE TITLE
[Feature]: Parallelisation of preproc_batch_tops.csh

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#246]
I have noticed that the preproc_batch_tops.csh script is severely limited by being single-thread. Perhaps a parallelisation of the loop could increase performance using GNU-Parallel? With a large stack of images this step takes a very long time.

I found a very old thread discussing this and the issues with variables set before and withing the loop here:

http://gmt.soest.hawaii.edu/boards/6/topics/4295

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, Yes, we did not split this as it only needs to be done once and usually the limiting issue is the I/O speed instead of threads as you could run all subswaths the same time. You could parallelize this with GNU-Parallel and modifying the align_tops.csh. The only difference between the two scripts (preproc and align_tops) is that preproc_batch_tops.csh stitches the frames together while coregistering. This is not required anymore as you could re-assemble the data with organize_files_tops[_linux].csh

**Comment by SteffanDavies** [comment]
I have been running GMTSAR on Cloud Compute environments with 16-32 cores and 128GB RAM and can confirm there is a lot of wasted performance here when working with large datasets (currently working with 151 SLC). Performance graphs show SSD bottlenecking during the unzipping phase but there is almost no I.O. bottleneck up to this step.

For now I will try to run all 3 SS at once but still there is room for improvement as CPU usage hovers around 10-15%. Considering the many hours this step takes for large datasets it could be advantageous to find a more multi-thread friendly solution. Also processing all subswaths may not be a requirement for certain AOIs.

> The only difference between the two scripts (preproc and align_tops) is that preproc_batch_tops.csh stitches the frames together while coregistering. This is not required anymore as you could re-assemble the data with organize_files_tops[_linux].csh

If this is the case then why does the S1 recipe say to perform organize_files_tops[_linux].csh before preproc_batch_tops.csh?  Should't it use align_tops.csh after organize_files_tops[_linux].csh considering the data is already re-assembled?

Thanks Eric

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @SteffanDavies, the preproc_batch code was written before the organize script. Essentially, if you area of interest is small, the two methods should work the same except you may waste some time re-running the msater image by using align_tops.csh, though the current distribution in master branch supports skip_master. However, if your area of interest is over 3-4 full frames (e.g. 40 bursts in one subswaths), then the organize script will need to be run with separate pins, and then one'll need to use preproc_batch script to piece things together. The reason is the normal tiff format could not support a single file larger than 4GB.

**Comment by Xiaohua-Eric-Xu** [comment]
As for further paralleling the script, you could try running multiple preproc_batch script even within one subswath. However, what we found is the IO is the real bottleneck. Further paralleling the script will not really help over that. (I usually run between 3-6 preproc_... jobs the same time, or preprocessing one frame while producing interferograms for another)

**Comment by SteffanDavies** [comment]
> As for further paralleling the script, you could try running multiple preproc_batch script even within one subswath. However, what we found is the IO is the real bottleneck. Further paralleling the script will not really help over that. (I usually run between 3-6 preproc_... jobs the same time, or preprocessing one frame while producing interferograms for another)

Calling [preproc_batch_tops.csh](https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/preproc_batch_tops.csh) multiple times in the same subswath & frame? Or the same subswath but in different frames? 
I am mostly working with single frame datasets with AOI sometimes covering only 1 Subswath, but very large periods (5+ years). I doubt I can repeatedly call [preproc_batch_tops.csh](https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/preproc_batch_tops.csh) in the same Subswath & Frame (F directory) right??

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @SteffanDavies, once you have your data.in file, you could split them in to a few (e.g. 5), with each having the top line being the master image. You'll need to run each preproc_batch_tops program in a subdirectory (with the correct files in them) and then move all the product to your raw directory afterwards.

**Comment by Xiaohua-Eric-Xu** [comment]
In fact, you don't have to really follow the upper level script to do the processing, especially when your AOI is small. The preproc_batch thing was mainly targeting larger area as a major effort was to figure out how to properly make alignment when frames are not fully matching each other (e.g. off by two bursts) and how to stitching things together properly (when you have multiple frames). For alignment of TOPS, align_tops.csh is much simpler. 
Essentially, the current master branch has the skip_master option which could allow you to do a batch alignment by playing with the proc_stage, skip_stage and skip_master (for a frame/bursts). I haven't write up a batch script to call these but the functions are available.
