### ISSUE TITLE
Issue with preproc_batch_tops.csh

### ISSUE THREAD

**Issue by egraves4** [gmtsar/gmtsar#291]
I followed the directions for Sentinel1 processing from the sentinel_time_series_2.pdf and I'm running into an issue when running the preproc_batch_tops.csh script. I've successfully run the script numerous times over the last couple years, and as recently as a few months ago. However, after linking the *iw1*vv*.xml and .tiff, corresponding *.EOF files from the main raw directory, and the dem to process in this case F1, I am getting these errors and the *.PRM files made only have three lines and the baseline file is empty. The other frames F2/F3 run as expected. 
![preproc](https://user-images.githubusercontent.com/55607435/156921099-89268018-a9ee-4a30-8272-490a1cd885bb.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, segmentation fault. Not sure what's the reason without further details. Have you considered deleting the entire raw folder and re-start? 
Could it be the EOF files? 
You could send over the xml and EOF files so I could give them a test, but since your F2 and F3 are running fine, I do suggest to delete and start all over.

**Comment by egraves4** [comment]
Thanks for taking a look, Eric. I deleted them and restarted, which worked.

**Comment by Xiaohua-Eric-Xu** [comment]
Cool! This trick never gets old.
