### ISSUE TITLE
[Help]: sbas **Segmentation fault(Core Dump)**

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#304]
Hi ，as the title says。

# input
>sbas intf.tab scene.tab 173 89 560 1260 -range 827307 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -atm 5 -rms -dem 

# output 
>compute RMS misfit
compute DEM error
setting smoothing to   5.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  40.000 degree 
setting range to 827307.000 m 
Memory Allocation Successful...
read table file ...
number of SAR scenes is 89 
Segmentation fault(Core Dump)段错误(吐核)

# Anyway I can do that?

**Comment by dsandwell** [comment]
This error occurs because the memory needed to store all the interferograms exceeds the memory of your computer.  If you have the latest GMTSAR from the github distribution there is a -mmap option that will use the local disk to store the interferograms and read them from the disk as needed.  Reading and writing to disk can be slow so the job may take a long time.

> On Mar 29, 2022, at 6:36 AM, SWJTU-jyliu ***@***.***> wrote:
> 
> 
> Hi ，as the title says。
> 
> input
> 
> sbas intf.tab scene.tab 173 89 560 1260 -range 827307 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -atm 5 -rms -dem
> 
> output
> 
> compute RMS misfit
> compute DEM error
> setting smoothing to 5.000
> setting radar wavelength to 0.055 m
> setting radar incidence angle to 40.000 degree
> setting range to 827307.000 m
> Memory Allocation Successful...
> read table file ...
> number of SAR scenes is 89
> Segmentation fault(Core Dump)段错误(吐核)
> 
> Anyway I can do that?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
