### ISSUE TITLE
[Help]: plot problem

### ISSUE THREAD

**Issue by 674111501** [gmtsar/gmtsar#339]
**Describe the problem you met**
When I get the corr result and plot it , I find there is something wrong in the image.There is a black line between two bursts.Is there any solution for it?Except for your reply.
**OS and software version**

If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![image](https://user-images.githubusercontent.com/69631148/172508030-64bfa7e5-cd27-43f9-acea-6d59cd8d6542.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
The darker line is because that is the burst boundary. The along track spectrum differs through that line, thus you'll have a low coherence seam. Another reason for some cases is that after stitching (default in the middle) the SLCs, the middle line maybe off for the master and aligned images. In this case, you'll lose a line (or a few lines) of phase as they are formed between forward looking and backward looking measurements. This should not affect much the amplitude and phase after filtering.

One solution is to form coherence first burst-wise and then do the stitching. Currently there's no automated script to so in GMTSAR. 

One could combine create_frame_tops.csh, preproc_batch_tops.csh, intf_tops.csh to form burst-wise interferograms, calculate the offset based on the PRF, clock_start in the PRM files, stitching the output corr.grd grids using GMT based on the calculated offset, and geocode with a new trans.dat calculated based on the modified PRM to account for the change in start and end time.

**Comment by 674111501** [comment]
I‘m sorry，but it’s hard for me to understand it.Is it mean rerun create_frame_tops.csh, preproc_batch_tops.csh scripts?

**Comment by Xiaohua-Eric-Xu** [comment]
Here are some basics of GMTSAR: https://topex.ucsd.edu/gmtsar/tar/GMTSAR_2ND_TEX.pdf
Here is a Sentinel-1 time-series document: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_4.pdf 
They may help a bit.
