### ISSUE TITLE
Problem merge frames Sentinel-1 

### ISSUE THREAD

**Issue by Fabiangeo95** [gmtsar/gmtsar#36]
Hi, I joined images using "create_frame_tops.csh", but when doing the interferogram (intf_tops.csh) the phase looks like this. I made sure the dem and orbit were fine. What could be causing the problem?
![Captura de pantalla de 2020-07-27 02-55-24](https://user-images.githubusercontent.com/68412610/88513989-4b72c900-cfb7-11ea-8259-36ab43ec372b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Feels like the coregistration did its job, otherwise you'll see burst boundaries. Is this tops data? I don't see bursts at start or end of the images. Normally when this happens, it's related to topo_ra.grd being incorrect. I am surprised that it ran through.
Maybe when you run intf_tops.csh, start with stage = 1 to remake the topo_ra.grd?
