### ISSUE TITLE
[Help]: SBAS outputs large jumps in displacement between consecutive dates, what to do?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#395]
I am applying the SBAS technique to highway displacement monitoring. The results show large jumps in displacement values for consecutive dates.

For example, this point has a jump of -3cm between the first and second date:

![Screenshot from 2022-08-02 15-58-31](https://user-images.githubusercontent.com/50405969/182406466-d6f64dd0-1f7c-4c88-a15c-a64f965a5234.png)

I have read that jumps greater than 1/4 of wavelength of the SAR wavelength correspond to error, so for Sentinel-1, one should disregard differences greater than 1.4cm between two consecutive dates, correct?

Are these large jumps due to the unwrapping? If so, how can they be minimized.

**Comment by Xiaohua-Eric-Xu** [comment]
> I have read that jumps greater than 1/4 of wavelength of the SAR wavelength correspond to error

I don't think this is a valid statement. In presence of atmospheric noise, it could be larger than 10-s of cm. And phase unwrapping errors could give jumps too. 

For localized defomation, try cutting to your AOI and detrend the data before putting things into sbas. And you may also want to tune the smoothness and -atm options to reduce such effect.

**Comment by SteffanDavies** [comment]
> > I have read that jumps greater than 1/4 of wavelength of the SAR wavelength correspond to error
> 
> I don't think this is a valid statement. In presence of atmospheric noise, it could be larger than 10-s of cm. And phase unwrapping errors could give jumps too.
> 
> For localized defomation, try cutting to your AOI and detrend the data before putting things into sbas. And you may also want to tune the smoothness and -atm options to reduce such effect.

My AOI is a road of hundreds of KMS that cuts diagonally through all 3 subswaths. I can't really cut it to a region, considering I'm merging all three at once. What do you consider "localised deformation"? I'm interested in local deformation over a linear asset with hundreds of km if that's what you mean.

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu I went back to check o SBAS parameters and I did not perform aps removal. I am redoing SBAS with -aps 3 to see if it makes a signifcant difference. I also applied -smooth 1, however isn't this a very artificial way of compensating for bad noise? 

Considering the nature of this study, I am very unsure on how to tweak GMTSAR SBAS parameters. Most studies and examples using GMTSAR are dealing with seismic or volcanic events, which is very different to what I'm trying to do (linear infrastructure comprising entire SLC). Do you have any tips?

**Comment by SteffanDavies** [comment]
I have also tried going the StaMPS route and using a mean value of all points as a reference, this made a huge difference in the dispersion of values between dates, here is an example:

Before subtracting average:
![Screenshot from 2022-08-03 14-56-41](https://user-images.githubusercontent.com/50405969/182626834-97658847-493a-47cd-96d0-e39324714437.png)

After subtracting average:
![Screenshot from 2022-08-03 14-55-23](https://user-images.githubusercontent.com/50405969/182626907-aa8b398c-9dae-4864-b35f-b8267ad47a4f.png)

This seems to show that there is a very constant difference between dates affecting most points, which when removed smooths out the time-series.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes submitting an average or a trend will definitely help. And your AOI is small and not small at the same time. Atmospheric noise will be a key issue I assume. In such scale, there may be tectonic motion too. 

Are you able to locate some permanent features that's stable over time? e.g. Oil tanks, buildings. Referencing to these features may give you a relative motion that makes more sense. I know there are folks that install corner reflectors nearby infrastructures to enhance the analysis. Some of them are used as reference and some are directly on the infrastructures. They are basically a piece of metal that reflects radar signals.

**Comment by SteffanDavies** [comment]
> Yes submitting an average or a trend will definitely help. And your AOI is small and not small at the same time. Atmospheric noise will be a key issue I assume. In such scale, there may be tectonic motion too.
> 
> Are you able to locate some permanent features that's stable over time? e.g. Oil tanks, buildings. Referencing to these features may give you a relative motion that makes more sense. I know there are folks that install corner reflectors nearby infrastructures to enhance the analysis. Some of them are used as reference and some are directly on the infrastructures. They are basically a piece of metal that reflects radar signals.

Subtracting the mean definately helps smooth the time-series and keeping a trend, however it can also cause some weird issues, like the massive uplift in the last date.

I could divide de results into portions of for example 10km and then try to find the closest building to reference to, or the most stable point along the road (based on standard deviation and average velocity, maybe???). 
But then how do I know if the building is stable enough to deserve being a point of reference? I was thinking about referincing to buildings with GPS installed but I might only have access to this data in the future. Installing corner reflectors with GPS will definitely be a possibility in the future.

**Comment by Xiaohua-Eric-Xu** [comment]
If you have GPS, then definitely use GPS. If you have lots of them, you could do an integration.

**Comment by SteffanDavies** [comment]
> If you have GPS, then definitely use GPS. If you have lots of them, you could do an integration.

Maybe in a few months, until then I have to make the most of what I have, unfortunately.

**Comment by mobigroup** [comment]
@SteffanDavies Maybe you'd use some seismic event interferogram to find the stable reference points with good coherency. For the example, I use this approach for mountain area divided by low-coherency forested area from coastal line which is often the recommended location for a reference point. See the notebook on Google Colab: https://colab.research.google.com/drive/1gr6pHFu1_gRltjfSuGLGoYqgwDQHNl5M?usp=sharing
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7342379/182838898-28fce19e-e18f-46cd-9407-b590ecec31b7.png">

As you see, the forest area with almost zero coherency produces fake movements with large amplitude. When we exclude low-coherency areas and use stable reference point we don't have any similar to 10 cm downset/upset in 2 weeks. Our correlation map is the key:
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/7342379/182840002-2737ea9e-44b9-4c10-b7e5-68ac5abd3ef9.png">

**Comment by SteffanDavies** [comment]
@ericlindsey is there any example comparing smoothness levels for a same dataset? It's hard to decide between values of 1 or less when I'm not really sure how it's going to affect the results.

**Comment by ericlindsey** [comment]
Smoothness levels in reference to what, exactly? Looking at your discussion so far, I think you are attempting a challenging task - as discussed, atmospheric noise can easily have amplitudes of several cm, or tens of cm, between individual dates. This is not an artifact of the processing or anything - it is a true signal delay caused by variable presence of water vapor, so there's not much we can do directly to remove it from the image. All methods developed so far are only approximate, and rely on things like spatial or temporal filtering, or weather model correction (but the weather models have a resolution of 50km pixel size or so). 

I think your proposed solution to divide the data up into smaller subsets, like 10km-segments, is a good one. Then, if you believe most of the road is stable, with only some unstable parts, you can subtract the average value (or a trend) across this segment from all points in it. Since the atmosphereic noise is usually spatially smooth over this length scale, it should remove most of the long-wavelength noise and then you can look for smaller-scale deformation features along your road.

A similar approach, proposed by @mobigroup in another thread, is to conduct spatial filtering of the whole image to remove all the long-wavelength atmospheric noise and keep only short-wavelength signals. This is effectively similar to dividing the image up into patches and removing a trend from each one, but you can do it across the whole image at once. This is what we often do when looking at small-scale tectonic signals too, like fault creep or a small earthquake.

Hope these suggestions are useful - you are doing a challenging project!

**Comment by SteffanDavies** [comment]
@ericlindsey Woops, I was going to quote @Xiaohua-Eric-Xu but my autocomplete decided to summon you instead. Not that I mind of course, considering you're in-depth answer. Thanks.

Most recent information about this AOI indicates that there are issues with snow cover during the winter, which I didn't know beforehand, that might explain a lot actually.

**Comment by Xiaohua-Eric-Xu** [comment]
> @ericlindsey is there any example comparing smoothness levels for a same dataset? It's hard to decide between values of 1 or less when I'm not really sure how it's going to affect the results, and I'm not even sure 1 is too severe.

I believe the smoothness is determined arbitrarily, which usually involves strong flavor of the person who does the time-series analysis. Some (like me) love to keep some scatters of data just to make sure the time-series is not over smoothed to avoid artificial signals. Some think deformation should be smooth over time thus does not like scatters in the data. If your target is to remove bump-like features (e.g. caused by an outlier), the atm correction algorithm in GMTSAR should be able to handle that, though it depends on connections on both side of that acquisition date (i.e. a bad day). 

I know someone who identify PS pixels using STAMPS and then take out those data (or masking the rest) and run this atm correction (see https://doi.org/10.1002/2017JB014620). It worked really well for his challenging area. Phase unwrapping is done after interpolating nearneighbor to these PS pixels with SNAPHU.

**Comment by SteffanDavies** [comment]
> > @ericlindsey is there any example comparing smoothness levels for a same dataset? It's hard to decide between values of 1 or less when I'm not really sure how it's going to affect the results, and I'm not even sure 1 is too severe.
> 
> I believe the smoothness is determined arbitrarily, which usually involves strong flavor of the person who does the time-series analysis. Some (like me) love to keep some scatters of data just to make sure the time-series is not over smoothed to avoid artificial signals. Some think deformation should be smooth over time thus does not like scatters in the data. If your target is to remove bump-like features (e.g. caused by an outlier), the atm correction algorithm in GMTSAR should be able to handle that, though it depends on connections on both side of that acquisition date (i.e. a bad day).
> 
> I know someone who identify PS pixels using STAMPS and then take out those data (or masking the rest) and run this atm correction (see https://doi.org/10.1002/2017JB014620). It worked really well for his challenging area. Phase unwrapping is done after interpolating nearneighbor to these PS pixels with SNAPHU.

My fear is that for continuous monitoring (every 2 weeks) a smooth factor too strong could disguise sudden acceleration which I would have to identify in case of potential landslide or other failure.

**Comment by mobigroup** [comment]
@SteffanDavies How about median filtering for the each pixel timeseries? For sbas baseline 65 days we have 5 pairs for every 12-days image and so use the median filtering with this window size to compensate atmospheric effects before SBAS processing. That works for nonlinear movements detection including seasonal ones (how about underground water reservoirs on your area, for the example?)

**Comment by Xiaohua-Eric-Xu** [comment]
> My fear is that for continuous monitoring (every 2 weeks) a smooth factor too strong could disguise sudden acceleration which I would have to identify in case of potential landslide or other failure.

If your target is detection on roads, have you thought about using gradient (strain) instead of absolute phase values (deformation), as in case of sharp change (sudden subsidence), they'll show up in gradient but not as much in radar phase. See left phase-gradient plot.

![image](https://user-images.githubusercontent.com/16844111/193128164-9242fc4b-9770-48eb-8ef9-96fd59fc035f.png)

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Please explain do you mean unwrapped phase gradient or raw phase gradient used for interferogram computing?

**Comment by Xiaohua-Eric-Xu** [comment]
Sandwell, D. T., & Price, E. J. (1998). Phase gradient approach to stacking interferograms. Journal of Geophysical Research: Solid Earth, 103(B12), 30183-30204.

**Comment by SteffanDavies** [comment]
> Sandwell, D. T., & Price, E. J. (1998). Phase gradient approach to stacking interferograms. Journal of Geophysical Research: Solid Earth, 103(B12), 30183-30204.

How can I obtain a phase gradient map in GMTSAR?

**Comment by mobigroup** [comment]
@SteffanDavies @Xiaohua-Eric-Xu It was discussed some years before and I think more than once. See just one link: #120 Also, phase gradient product is noted here: https://topex.ucsd.edu/gmtsar/ I’m going to add the calculation (optional) to PyGMTSAR because it looks more straightforward to exclude phase unwrapping for some cases.

**Comment by Xiaohua-Eric-Xu** [comment]
> > Sandwell, D. T., & Price, E. J. (1998). Phase gradient approach to stacking interferograms. Journal of Geophysical Research: Solid Earth, 103(B12), 30183-30204.
> 
> How can I obtain a phase gradient map in GMTSAR?

For the moment you could just turn on compute_phase_gradient in the config file for p2p_processing.csh. If you look into the script it basically added on parameter to filter.csh to activate certain lines of code.

**Comment by SteffanDavies** [comment]
> > > Sandwell, D. T., & Price, E. J. (1998). Phase gradient approach to stacking interferograms. Journal of Geophysical Research: Solid Earth, 103(B12), 30183-30204.
> > 
> > 
> > How can I obtain a phase gradient map in GMTSAR?
> 
> For the moment you could just turn on compute_phase_gradient in the config file for p2p_processing.csh. If you look into the script it basically added on parameter to filter.csh to activate certain lines of code.

Do you have a tutorial for P2P processing with S1 tops?

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu @SteffanDavies Could you explain the decimation factors and filters for the phase gradient calculation? I suppose idec=4 and jdec=1 to define almost square pixels, right? And what mean xdir and ydir filters here?

```
  set filter4 = $sharedir/filters/xdir
  set filter5 = $sharedir/filters/ydir
```

```
#
#  make the custom filter2 and set the decimation
#
  make_gaussian_filter $1 $dec_rng $az_lks $3 > ijdec
  set filter2 = gauss_$3
```

```
#
# also compute gradients and filter them the same way
#
  if($compute_phase_gradient != 0) then
    echo "filtering for phase gradient . . "
    conv 1 1 $filter4 real_tmp.grd xt.grd=bf
    conv 1 1 $filter5 real_tmp.grd yt.grd=bf
    conv $idec $jdec $filter2 xt.grd=bf xreal.grd
    conv $idec $jdec $filter2 yt.grd=bf yreal.grd
    rm xt.grd yt.grd
    conv 1 1 $filter4 imag_tmp.grd xt.grd=bf
    conv 1 1 $filter5 imag_tmp.grd yt.grd=bf
    conv $idec $jdec $filter2 xt.grd=bf ximag.grd
    conv $idec $jdec $filter2 yt.grd=bf yimag.grd
    rm xt.grd yt.grd
  endif
```

```
cat /usr/local/GMTSAR/share/gmtsar/filters/xdir 
17	1
  -2.8580304317007326e-03
  -1.8456092566716510e-03
   2.1764579221615073e-02
  -2.1530490335147274e-02
  -3.0529940042665758e-02
   8.7413051581473736e-02
   2.4469607245389439e-02
  -6.7318181998379500e-01
   0.0000000000000000e+00
   6.7318181998379500e-01
  -2.4469607245389439e-02
  -8.7413051581473736e-02
   3.0529940042665758e-02
   2.1530490335147274e-02
  -2.1764579221615073e-02
   1.8456092566716510e-03
   2.8580304317007326e-03
```

<img width="559" alt="image" src="https://user-images.githubusercontent.com/7342379/198510905-0ed040bd-0b48-44d4-9743-023c0d25f3d7.png">

ydir is inverted version of xdir due to flipped vertically data storing order.

**Comment by Xiaohua-Eric-Xu** [comment]
The xdir and ydir are just FIR derivative filter designed by a Matlab tool. Decimation does not have to be a square by the way. Usually if you want to detect very small changes, you want to use highest resolution and smallest pixel size, but taking the derivative also means magnifying noise, and larger pixel size (or decimation or filtering) can mitigate this effect. There is a trade-off.

**Comment by Xiaohua-Eric-Xu** [comment]
> > > > Sandwell, D. T., & Price, E. J. (1998). Phase gradient approach to stacking interferograms. Journal of Geophysical Research: Solid Earth, 103(B12), 30183-30204.
> > > 
> > > 
> > > How can I obtain a phase gradient map in GMTSAR?
> > 
> > 
> > For the moment you could just turn on compute_phase_gradient in the config file for p2p_processing.csh. If you look into the script it basically added on parameter to filter.csh to activate certain lines of code.
> 
> Do you have a tutorial for P2P processing with S1 tops?

Not for the moment, for the short course, I think we do have a demo but it's not written anywhere except the recordings from UNAVCO.
