### ISSUE TITLE
[Help]: landmask_ra.grd vs mask_def.grd

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#398]
The Sentinel-1 recipe is ambiguous on the use of masks. 
Before branching between unwrapping areas of good or bad coherence, it is suggested to create a landmask and linking the file to all subdirectories through the created “unwrap_intf.csh" script. 
Then, in the subchapter dealing with areas of poor coherence, it is sugested to create a coherence mask, and also link it to subdirectories in the "“unwrap_intf.csh", however, the line for the landmask is no longer there.

So should we do both or choose one of these approaches?

**Comment by mobigroup** [comment]
@SteffanDavies Landmask applied to phase and the mask applied to correlation before unwrapping. As I think SNAPHU ignores NODATA for correlation and for phase input datasets by the same way but I didn't check it.

**Comment by mobigroup** [comment]
Aha, one more addition - mask grid from interferogram processing is actually useless because it’s already applied to phasefild grid. So phasefilt grid NaN values are the same as mask grid NaNs. This grid excluding can significantly reduce the required disk space for Google Colab processing or big timeseries analysis everywhere.

I think a single composite correlation mask is the right solution. I’ve tested it and it works as expected. phasefilt should be just zero-filled in place of NaN values.

**Comment by Xiaohua-Eric-Xu** [comment]
> As I think SNAPHU ignores NODATA for correlation and for phase input datasets by the same way but I didn't check it.

I think SNAPHU will consider NaN as zeros or it does not take in NaN values.

**Comment by Xiaohua-Eric-Xu** [comment]
> The Sentinel-1 recipe is ambiguous on the use of masks. Before branching between unwrapping areas of good or bad coherence, it is suggested to create a landmask and linking the file to all subdirectories through the created “unwrap_intf.csh" script. Then, in the subchapter dealing with areas of poor coherence, it is sugested to create a coherence mask, and also link it to subdirectories in the "“unwrap_intf.csh", however, the line for the landmask is no longer there.
> 
> So should we do both or choose one of these approaches?

I don't think the low coherence mask contradicts the landmask. They both are applied to the interferogram. One for masking "bad" pixels and one for wet area.

**Comment by mobigroup** [comment]
> I think SNAPHU will consider NaN as zeros or it does not take in NaN values.

NODATA=0 for snaphu (NaNs are not allowed).

About phase mask please pay attention NODATA value is zero for snaphu and that’s still valid phase value. So masked phase should be processed as constant phase areas instead of NODATA areas and it might produce unwrapping artifacts. So we have just one way to use zero correlation mask because zero correlation areas are trustless. The phase image needs to be used as is without modification and correlation to be zero-masked for missed phase values (NaNs), water surface and so on.

**Comment by mobigroup** [comment]
See the example how to mask for unwrapping correlation grid only:
![image](https://user-images.githubusercontent.com/7342379/183407815-f9deff06-b03e-4f36-ade1-03b4be28a135.png)
Here again I use fast matrix operations for the inverse geocoding as for the direct geocoding. And of course we can apply the mask to interferogram too:
![image](https://user-images.githubusercontent.com/7342379/183407908-eb63a125-5d12-444a-8f58-de07aa3c5049.png)
For stack correlation mask it's even easy because we already have correlation in radar coordinates to create the mask.

The Live examples available as Jupyter notebook on Google Colab: https://colab.research.google.com/drive/1NjWXrMkFRB6E0-gViBLmmxprTqqRbDl5?usp=sharing
and
https://colab.research.google.com/drive/1oYHzNeH5mLuYFXcUxCGDrVBQYm9PUEfK?usp=sharing

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu Is there any difference between using a same threshold for snaphu or correlation stacking? When applying mask_def snaphu should be very low (like 0.001) but doesn't it do the same thing?

Ex:
snaphu_interp.csh 0.1 0 
vs.
gmt grdmath corr_stack.grd 0.1 GE 0 NAN = mask_def.grd

**Comment by SteffanDavies** [comment]
@mobigroup That makes sense, I have much fewer points using snaphu threshold vs mask_def on roads. I'm going to use mask_def from now on.

I'm closing the thread, thanks!
