### ISSUE TITLE
[Help]: absolute phase change recovery

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#409]
There is the paper which I'm trying to apply on a practice:

> Xu, X., & Sandwell, D. T. (2019). Toward absolute phase change recovery with InSAR: Correcting for earth tides and phase unwrapping ambiguities. IEEE Transactions on Geoscience and Remote Sensing, 58(1), 726-733.

As I understand this is the technique for 3D phase unwrapping on top of SNAPHU results. That's nice but I see some not intuitive technical points which are listed below.

Testing on GMTSAR example dataset S1A_Stack_CPGF_T173 and filtering too noisy images we can have 5 good enough interferograms. The mean differences between unwrapped phases divided by PI are
[-0.332, -1.008, 1.322, 0.324]
Really, we have here 1*PI changes twice (vs more intuitive n*2PI) as explained in the paper. At the same time, it looks weird for me because when SNAPHU unwrapping starting from a random point (it could start from the same corner but still needs to find a valid point which position is different between the interferograms) we can't have the nPI difference. And even more problems when interferogram includes some unconnected areas. Could you explain how and when is it possible to have the nPI difference?

Also, detrending interferograms we have the differences almost equal to zero, of course. Almost all GMTSAR tickets recommend to use detrending but it makes the absolute phase change analysis impossible. Even de-averaging removes the required information. Does it mean that we need to save the mean value while detrending?

**Comment by Xiaohua-Eric-Xu** [comment]
It should be N*2Pi instead of N*Pi. For the moment, I would not use this correction pixel-wise as there being a dilemma, i.e. if you filter the interferogram, the phase will not close to zero or 2N*Pi pixel wise; and if you don't filter, unwrapping is almost impossible for many areas. Thus we suggested to use it for the entire interferogram or blocks of areas with non-closure phase. What SNAPHU does is adding or subtracting 2N*Pi over each pixel, thus if you wrap the phase back, you'll get essentially your input (this has nothing to do with the reference pixel). 

Detrending or de-averaging should be done after this correction, not before.

**Comment by mobigroup** [comment]
Thanks, I really missed some points.
