### ISSUE TITLE
[Help]: When is it reasonable to detrend unwrapped phase?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#414]
I have been exploring the possibility of detrending unwrapped interferogram phase before running SBAS. 

The code for detrending in snaphu_interp.csh has been commented out, and based on previous discussions on this forum, and from what I understand, detrending is not always a reasonable approach if there are areas with significant active deformation. However, for "localized deformation" detrending is acceptable to improve SBAS results. 

Thus I have a few questions regarding detrending of unwrapped phase, when applying SBAS to infrastructure monitoring and non geological events:

1. When referring to detrending for localized deformation, does this mean very small AOIs (small unwrapped areas), or non-seismic / volcanic study cases where specific point values are important? I'm having difficulty undestanding what "localized" means exactly.
2. If no significant geological effects are expected (tectonic, seismic, volcanic movement or other), would it be acceptable to detrend and entire subswath (or multiple merged subswaths) for studying long linear infrastructure (long roads or railways going all the way across the SLC).
3. How does detrending affect APS estimation and removal accuracy?

**Comment by Xiaohua-Eric-Xu** [comment]
1. As long as it is not large scale tectonic deformation, i.e. you are working with a plate boundary, and your area is fully covered by your interferogram with some non-active ("quiet") area surrounding it, you should be safe to do detrending.
2. You need to always merge and then unwrap and detrend. Otherwise, you may end up with different trends removed across the subswaths.
3. Since trend is the lowest order component in an interferogram, and should satisfy the prerequisite of phase closure, thus should not affect APS mitigation.

**Comment by mobigroup** [comment]
@SteffanDavies For the case of infrastructure monitoring gaussian filtering in rolling window detrending looks safe. You don’t worry when your road moving as a single object (due to tectonic plates drifting for an example). You need to detect significant or fast local deformations only because small and slow deformation are not dangerous (like to common seasonal movements). In addition or instead of moving gaussian filtering we can fit the area to topography and/or coordinates to find and remove the global trends too. By the way, average value removal is a case of detrending of course (affecting the 1st moment only). And for strong nonlinear deformations that’s almost impossible to hide the effect by detrending (for an example a set of fractures is fractality object and that means 3rd moment is not zero but gaussian filtering affects the 1st and 2nd moments only).
