### ISSUE TITLE
[Help]: i wanna check coordinate of my AI, but phase.filt.grd is not exist in merged interferogram folder as toturial, it's belong to folders not merged.what's wrong.

### ISSUE THREAD

**Issue by joejoe03050709** [gmtsar/gmtsar#420]
![5P0AG LDX}1I~@MMA2SGO)M](https://user-images.githubusercontent.com/111356557/187655648-436a1eeb-b696-4722-a22a-1d47c350e236.png)

![5P0AG LDX}1I~@MMA2SGO)M](https://user-images.githubusercontent.com/111356557/187655648-436a1eeb-b696-4722-a22a-1d47c350e236.png)
![JIKJCMY(~QV$HAC_XF 7C%O](https://user-images.githubusercontent.com/111356557/187654803-dae2f5aa-2c3e-4f13-8189-ad275ee423de.png)

**Comment by Xiaohua-Eric-Xu** [comment]
something went wrong in your processing so no grids generated in the merge directory. 
Check on your log files of 
1) interferogram production
2) merging
and see what they say inside.

**Comment by joejoe03050709** [comment]
> something went wrong in your processing so no grids generated in the merge directory. Check on your log files of
> 
> 1. interferogram production
> 2. merging
>    and see what they say inside.，

sir, i did snaphu directly，is that ok？and there is a problem after i masked areas. i checked landmask step and don''t know what's going on.
![UAV5JGT_U}NY157OW2%Y2S3](https://user-images.githubusercontent.com/111356557/188120062-c576120a-2f99-475b-ad91-7d1e7d63765a.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. It could be that the landmask_ra.grd has some strange starting values of x/y (i.e. 1e-7 instead of 0, you could check this with `gmt grdinfo`). One way of fixing this is to run landmask.csh but with larger size than specified by the range of e.g. phasefilt.grd. A buffer around the mask will fix this problem. i.e landmask.csh -500/xmax+500/-500/ymax+500
