### ISSUE TITLE
[Help]:interferogram

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#499]
Hello everyone 

1. when i run this script select_pairs.csh baseline_table.dat 75 150 in F2 and F3. the value in baseline_table.data it changed between F2 and F3 is there any problem in that?
How will I merge the sub swath if these values ​​are different?
![image](https://user-images.githubusercontent.com/108739411/196938021-81f03566-1906-413b-8ffb-c42c19d8b8c0.jpeg)
2. Also the number of interferogram is different between f2 and f3
In F2 (166)
In F3 (168)
![image](https://user-images.githubusercontent.com/108739411/196938075-d7bd1ff0-1254-45a0-8f29-b27bbe4d042d.jpeg)
3. some of folders interferogram
‏corr.pdf appears in black
![image](https://user-images.githubusercontent.com/108739411/196938090-ffc4c863-d70d-4867-9cfd-64b908e76265.jpeg)

**Comment by Obaida777** [comment]
Actually, the same problem happened with my.

**Comment by mobigroup** [comment]
@Alzaidy1 @Obaida777 you’d try PyGMTSAR (Python GMTSAR) with user friendly interactive processing in Jupyter Python Notebooks, see Google Colab examples to start: https://github.com/mobigroup/gmtsar There is also public Docker image to run the notebooks locally in the preconfigured container without software installation: https://hub.docker.com/r/mobigroup/pygmtsar

**Comment by Obaida777** [comment]
Dear Mr @mobigroup Do you have full tutorial to flow the steps for Linux or windows. 

Regards

**Comment by mobigroup** [comment]
@Alzaidy1 
> Actually I don't have the full knowledge about the scripts that are used to make SBAS by pygmtsar

There is the notebook "GMTSAR example dataset S1A_Stack_CPGF_T173" on the GitHub project page:

![](https://user-images.githubusercontent.com/7342379/189961167-bf3901e5-417c-41ce-a5ca-d1c74c239a04.png)

See also Python console script for the same processing: https://github.com/mobigroup/gmtsar/blob/master/tests/S1A_Stack_CPGF_T173.py

The same example is available as a set of GMTSAR scripts too, see the archive http://topex.ucsd.edu/gmtsar/tar/S1A_Stack_CPGF_T173.tar.gz That's easy to reproduce inside GMTSAR Docker image: https://hub.docker.com/r/mobigroup/gmtsar

![](https://user-images.githubusercontent.com/7342379/195099112-6bccc8e5-a57c-4189-ad94-c3fa9a10b891.jpg)

@Obaida777 
> Dear Mr @mobigroup Do you have full tutorial to flow the steps for Linux or windows.

You just need to open the live example and read the notes and the code. And you are able to convert the examples to PDF files if you really need to print them to read...

**Comment by kguns32** [comment]
Hi there -- it sounds like you've got some help already, so hopefully that worked for you guys, but to answer your original question, to maintain the same number of interferograms in each subswath for a time series, the time series documentation (https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf ) says to only run select_pairs.csh in your first subswath and then copy the output intf.in file to the next subswath, and substitute the F* values inside it to the specific subswath. 

For your purposes it sounds like you're only running two subswaths, F2 and F3. So I would run select_pairs.csh in F2 and then copy intf.in to F3 and edit the intf.in in F3 to refer to the S1_*_ALL_F3 file stem names instead of the F2 files stem names (see page 16 and 17 in the time series document above).

**Comment by Obaida777** [comment]
Dear @kguns32 we are already Run  select pairs in F1 and  F2 paths but the baseline_table contains are Different in each sub swath (F1,F2), and when we move intf.in from F1 to F2 and Run interferogram some of the folder is Empty,  and some time the interferogram file(corr.pdf ) is completely black , what do you think  problem is?

**Comment by chintals** [comment]
> Dear @kguns32 we are already Run select pairs in F1 and F2 paths but the baseline_table contains are Different in each sub swath (F1,F2), and when we move intf.in from F1 to F2 and Run interferogram some of the folder is Empty, and some time the interferogram file(corr.pdf ) is completely black , what do you think problem is?

The baseline table uses the satellite clock start and end time which is different for each subswath, so the parallel and perpendicular baseline will be different for each swath. That's not an issue.

However, intf.in generated in the first swath, should be copied over to other swath folders and the F* in the intf.in file should be the same a F* of the swath. After copying the intf.in file, open it, and use find and replace (in the text editor) to match F* with swath F*

**Comment by Obaida777** [comment]
Hi @kguns32 Actually i run select pairs in both F1 and F2 after that i copy intf.in from F1 directory to F2 and change F1 to F2 inside the file.

**Comment by Obaida777** [comment]
Hi @chintals did i should Run select pairs in both F1 and F2 right ? And replace intf.in inside F2 with intf.in from F1?

**Comment by chintals** [comment]
No, run select_pairs.csh in F1, which will generate intf.in, copy that intf.in file to F2 and replace all F1 entries to F2

**Comment by Obaida777** [comment]
@chintals  Thank you for your responding 🙏

**Comment by chintals** [comment]
Yes,  the baseline_table from F1 will later be used prior to sbas run.

**Comment by Xiaohua-Eric-Xu** [comment]
Here are some more information to consider. The parameters are different. Other that what @chintals said about the starting time, which I think should have little effect on the numbers, in fact, when you move from one subswath to another subswath, these numbers are supposed to change. Because these numbers (perpendicular and parallel baseline) should change with incidence angle. They may not be representing different baseline, but when you select a different subswaths (or incidence angle), these numbers will change correspondingly. Thus for a multi-subswath scenario, it's better to use the one in the middle and duplicate the selected pairs for other subswaths.
