### ISSUE TITLE
intf_tops.csh: no landmask is applied with region cut to snaphu

### ISSUE THREAD

**Issue by Loganator17** [gmtsar/gmtsar#56]
Greetings Dr. Xu, Dr. Sandwell, or anyone else who might know how to help me!

I'm trying to interfere and unwrap multiple Sentinel 1 interferograms with intf_tops.csh. I've been using GMT6.1.1 with GMTSAR 6; we installed the most up to date version of GMTSAR 6 this weekend. This area we are surveying are in the Aleutian Islands. Running this program with a landmask seems important for minimal unwrapping errors. 

I can't seem to apply the landmask prior to calling to snaphu_interp.csh. I am seeing lines 193-205 in intf_tops.csh have some commented out sections; as well, landmask.csh doesn't seem to have a $region_cut being applied to it.
 
I've tried to edit this script by removing the #'s in line 195-197 out; 
I've also tried to apply the $region_cut to landmask.csh in line 200 
I found an older forum post that seems to highlight the [same issue](http://gmt.soest.hawaii.edu/boards/6/topics/6338). When I tried this manual method, my landmask_ra.grd was removed from the topo directory during processing, and again no landmask was applied prior to the unwrap.

Is there a known solution, even a manual one, that might help me unwrap with the landmask_ra.grd applied? 

Thanks in advance. 

Logan, in Fairbanks AK

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Logan,
Thanks for finding this out for us.
I changed the region_cut parameter to cut SLC instead of cutting interferogram before snaphu.csh. This will speed processing up when you are focusing on a very small area.
You are right that I forgot to specify the parameter for landmask.csh (maybe deleted it by mistake). I made an update for intf_tops.csh in the master.
Cheers,
Xiaohua(Eric)

**Comment by Loganator17** [comment]
Thank you, this solved my issue!
