### ISSUE TITLE
[Help]: SBAS interferograms proc_stage parameters

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#634]
I was a bit confused about page 19 of the documentation https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf
“Check that the other parameters are set correctly and that proc_stage = 1 for the first interferogram, and then modified to 2 for the full set.”
May I ask whether to run proc_stage = 2 after proc_stage = 1 is finished??

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, it's better to do that as step 1 will do back geocoding on the topographic information, which will be used to remove topographic phase for interferograms. I know this step may take a while but you only need to run that once.

**Comment by Yaoshangheng** [comment]
That's alright，then I do my process：
step1 ：set pro_stage = 1 of the “batch_tops.config” files,and run command “intf_tops_parallel.csh intf.in batch_tops.config 4” from F1,then I got  result in the intf_all directory which include interferogram pair. fig.1
![1](https://user-images.githubusercontent.com/20898434/218355339-9c117c4d-a89b-489c-8ae3-b3dbbd8fd7b3.jpg)
                                                            fig.1

step2 ：set pro_stage = 2 of the “batch_tops.config” files,and run command “intf_tops_parallel.csh intf.in batch_tops.config 4” from F1，then I got  result in the intf_all/2019003_2019015 directory which include 2019003_2019015 interferogram pair directory.fig.2
![2](https://user-images.githubusercontent.com/20898434/218355796-d316be2c-c8cb-4a38-b483-0555c51f6dd7.jpg)
                                                            fig.2

While those result files shows in the "intf_all/2019003_2019015/2019003_2019015"   folder seem the same as "intf_all/2019003_2019015".fig.3
![3](https://user-images.githubusercontent.com/20898434/218356673-2f58ef64-1546-4af5-a927-82a6e89aeeff.jpg)
                                                             fig.3

It's that alright？

Best wishes!

**Comment by igps-ftk** [comment]
1). In the first step (proc_stage = 1), run intf_tops.csh only for one interferogram, e.g., intf_tops.csh intf.in.one batch_tops.config.
2). Change  proc_stage from 1 to 2
3). Now you can process other interferograms in the parallel mode. If some interferograms already exist in intf_all , the new result will be put under the old directory. And if you process it again (the third time), an error will occur when moving it to intf_all because the target already exists and mv command will not overwrite it by default . 

You can do the back geocoding manually, using the code in intf_tops.csh.  And set proc_stage to 2. Then run the intf_tops_parallel.csh directly.

Cheers,
Yunfeng Tian

**Comment by Yaoshangheng** [comment]
I see!Thank you all for your help
