### ISSUE TITLE
[Feature]: some questions

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#637]
I would like to ask you some questions, please answer them urgently. Thank you!
1. GMTSAR when dealing with the settlement rate of the study area, the following questions arise:
(1) There is a large area of settlement in the study area, and the location is wrong. Compared with previous data, it is found that only one place is prone to subsidence in the study area. Why is that?
(2) There are more correlation points in the results after atmospheric correction, but after sbas processing, there are fewer correlation points in the study area and most blank areas in the middle. In addition, there is an obvious subsidence area in the study area, but it does not appear in the results of SBAS. Why is that?
(3) In the process of sbas processing: compared with the results of sbas processing, the results obtained by SBAS-ATM are less ideal. Shouldn't the results be better after CSS atmospheric correction?
2. GMTSAR itself has a lot of bugs and is used by fewer people around, mostly using GAMMA to process data. Do GMTSAR have an advantage in dealing with subsidence data?
3. Download SAFE data from ASFA (two adjacent study areas) and use GMTSAR to desist from the response area. So how do you fuse the settlement results of adjacent study areas?

I am looking forward to receiving your reply. Thank you for your patient answers.

**Comment by kjz1997** [comment]
1，I think GMTSAR is better open source. The GAMMA you mentioned is commercial software that not everyone can use. GMTSAR gives users more creative space. You can write scripts and read source code to improve. The quality of a software does not depend on the number of users. GMTSAR also provides users with a very friendly communication platform. 
2，As for the bugs you mentioned, almost all the problems I have encountered are caused by my own operation problems. The only thing I think is that the running memory requirements are very high. If you process a large number of images, you may need a workstation
3，The difference in results may be due to the difference in software use, parameter setting or experience. There are many parameters in GMTSAR that need to be set. For these parameters, I think we should carefully read the meaning of each parameter, and what corresponds to setting and not setting, rather than attribute the results to software.
4，The above new feelings from using GMTSAR are welcome to discuss with each other.

**Comment by Luvina0503** [comment]
@kjz1997 
In this process, I set the following parameters: select the main image; Set time baseline and vertical baseline; Setup parameter file batch_tops.config; Unwinding threshold. But I feel like the parameters are pretty much fixed, so I can't figure out where the parameters are causing the problems. Have you encountered any of these problems?

**Comment by Luvina0503** [comment]
@kjz1997 
Steps of my operation: Simple align (preproc_batch_tops_esd.csh), re-align image (preproc_batch_tops_esd.csh), generate intf.in(select_pairs.csh), interfere (intf_tops.csh), and unwrap (unw) rap_intf.csh), GACOS Correction (GACOS_correction.csh), sbas Correction (sbas)

**Comment by kjz1997** [comment]
Should atmospheric correction not correct the phase after interference and before unwrapping?

**Comment by Luvina0503** [comment]
@kjz1997 
I'll give it a try. Maybe that's partly why my results aren't so good. Thank you very much

**Comment by Luvina0503** [comment]
@kjz1997 @Xiaohua-Eric-Xu 
https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/snaphu.csh
https://github.com/esrivas17/gacos_correction_for_GMTSAR/blob/master/operation.csh
figure1 ：snaphu.csh
![E0F$6G87TDPZ2KC2H$~X}JV](https://user-images.githubusercontent.com/114629377/218911502-608b0740-0bf5-4275-b7c4-75850f7c7cc3.png)
figure 2 : the script for GACOS correction
![FRBALHM7 3W3V6QJB DFBPC](https://user-images.githubusercontent.com/114629377/218911580-dd5734d6-5fdf-4749-8e66-f9b9ad978b89.png)

If I do the GACOS correction first, I get the corrected result in the red box in Figure 2. Should phasefilt.grd in the red box in Figure 1 be replaced with the corrected result (red box in Figure 2) during the unwinding phase?

**Comment by kjz1997** [comment]
yes,I found this issue while using the script, I made modifications to the snaphu.csh script. But the results were not ideal,I don't know if it's a problem with my operation.

**Comment by Luvina0503** [comment]
@kjz1997 
I'll give it a try and see what happens

**Comment by Xiaohua-Eric-Xu** [comment]
> I would like to ask you some questions, please answer them urgently. Thank you!
> 
> 1. GMTSAR when dealing with the settlement rate of the study area, the following questions arise:
>    (1) There is a large area of settlement in the study area, and the location is wrong. Compared with previous data, it is found that only one place is prone to subsidence in the study area. Why is that?
>    (2) There are more correlation points in the results after atmospheric correction, but after sbas processing, there are fewer correlation points in the study area and most blank areas in the middle. In addition, there is an obvious subsidence area in the study area, but it does not appear in the results of SBAS. Why is that?
>    (3) In the process of sbas processing: compared with the results of sbas processing, the results obtained by SBAS-ATM are less ideal. Shouldn't the results be better after CSS atmospheric correction?
> 2. GMTSAR itself has a lot of bugs and is used by fewer people around, mostly using GAMMA to process data. Do GMTSAR have an advantage in dealing with subsidence data?
> 3. Download SAFE data from ASFA (two adjacent study areas) and use GMTSAR to desist from the response area. So how do you fuse the settlement results of adjacent study areas?
> 
> I am looking forward to receiving your reply. Thank you for your patient answers.

For your questions, here are some answers, and hopefully they are helpful: 
1. (1). I am not sure whether you mean a geo-location error or the subsidence happens to be at a location where you don't expect. The former is quite rare that only occurs when a wrong timing or trans.dat file is used. The latter is likely due to errors in time-series analysis if you are certain of the location.
(2). I am a bit confused by your statement as atmospheric correction should not affect image correlation. The blank in your velocity grid is likely because you did not use a common-coherence mask during phase unwrapping. Since the atm correction approach requires every interferogram have pixels that are valid in every interferogram, if you have decorrelation here and there inconsistently through time, then that pixel highly likely will have a NaN as output. 
(3). The paper that discussed about the algorithm requires lots of pairs that have equal time-span on each side of an acquisition. In other words the connection (of your interferograms) will affect the atm correction.
2. If you attributes all undesired results to bugs, I don't know how to solve that. Many of the radar algorithms requires some knowledge to perform and they are reflected in parameter selection. GAMMA is a great software but it is commercial and lots of folks, research-wise or educational, could not afford such software for their study or teaching. GMTSAR is not a perfect software and a lot of modules could be refined, but being open source mean anyone with interest could take, modify and redistribute the code easily, with no restrictions. If you do not want to bother learning the details, feel free to take other folks implementation that may have made it more user friendly. Our goal at the moment is to make it as easy as possible for users to develop their own processing chain using the modules in GMTSAR. 
3. Usually we would fuse the data first before running processing. For TOPS data, try organize_files_tops[_linux].csh or create_frame_tops.csh and then run your processing chain.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
OK.Thank you for your answer

**Comment by Gigi-gugu** [comment]
> @kjz1997 I'll give it a try and see what happens

Excuse me, I wanted to ask you how the final result was? Did you modify the script? Can you share with me how you did it?

**Comment by kjz1997** [comment]
> > @kjz1997 I'll give it a try and see what happens
> 
> Excuse me, I wanted to ask you how the final result was? Did you modify the script? Can you share with me how you did it?

I don't know what you want to do. If you just want to use atmospheric corrected products for deformation calculation, you can take a look at the SBAS script to identify what the suffix of the unwrapping file looks like, and then change the atmospheric corrected suffix to the one required in the SBAS script. Alternatively, you can see what the suffix of gmtsar after unwrapping looks like and change the suffix in the atmospheric correction script.
