### ISSUE TITLE
Phasefilt_mask_ll 

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#659]
Hi,I am a new on GMTSAR,here is one of my interferogram does it  look alright？(date range:20190104-20190128)
How do I evaluate the quality of the interference on one interferogram?
![phasefilt_ll](https://user-images.githubusercontent.com/20898434/220901878-4a8cc68f-ceee-4f20-a181-5d14f4adda6c.jpg)

Best wish!

**Comment by Xiaohua-Eric-Xu** [comment]
This seems to be more appropriate for discussions (https://github.com/gmtsar/gmtsar/discussions) rather than issues. None the less, how to evaluate the quality of an interferogram is a tricky question. Usually an interferogram is a one time measurement that's hard to get a good uncertainty estimate. Correlation is a good indicator but does not reflect any atmospheric noise info. I guess with time-series you could do much more.
