### ISSUE TITLE
[Help]: GMTSAR two processing runs with different results

### ISSUE THREAD

**Issue by JPPereira93** [gmtsar/gmtsar#678]
Hello!

I have a question about two gmtsar SBAS processing runs that I've made. One with 2 year time span and the other with 3 year time span.

However, when comparing the same points throughout both analysis, in the same time window common to both, the displacement values are way different.

I understand that SBAS measurements are always relative, however shouldn't it be expected to at least have a constant offset through the both timeseries? Both analysis have the same interferogram pairs.

I present some screenshots with the two analysis, in the same point, with the same orbit and in the same time window:

![gmtsar_3_pontos](https://user-images.githubusercontent.com/90710707/223143502-37730956-a808-47fa-8263-ea22ddef6192.png)

Best regards,

João Pereira

**Comment by Xiaohua-Eric-Xu** [comment]
SBAS is a global solution (for a given point), which means later inputs may have effects to earlier solutions (in time). A typical way of passing such effect could be from smoothness and interferometric pairs. For the sbas program in gmtsar, if -atm is turned on, it'll estimate APS in a certain order (largest noise gets estimated and removed first), so the time-series could be different. Also the smooth factor is the relative weigh of the smooth matrix to the Green's matrix, thus setting the same smooth factor maynot ensure exact same smoothness when both matrixes increase in size. 

One way of examining whether the solution is robust, is to run with -smooth 0.0001 (0 sometimes may cause instability issue due to rank deficiency) and then turn off -atm. This will be the raw sbas time-series for a fair comparison.

**Comment by JPPereira93** [comment]
Thank you @Xiaohua-Eric-Xu, I will make those tests !

**Comment by mobigroup** [comment]
@JPPereira93 Maybe did you miss detrending step? See the difference between unwrapped phase as is and its detrended version in the Google Colab interactive notebook: https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing
Also, more SBAS pairs usually mean better results because the worst interferograms can be excluded. This Docker image provides SBAS processing for some dozens of interferograms with high resolution (15m) with detrending and some additional checks: https://hub.docker.com/r/mobigroup/pygmtsar-large Also, the notebooks available on GitHub too: https://github.com/mobigroup/YamchiDam/tree/main/notebooks

**Comment by Xiaohua-Eric-Xu** [comment]
@mobigroup detrending should not affect this comparison. The differences come from using part of the data or all the data, and detrending has nothing to do with any part of that.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu detrending moves average value to zero excluding 2pi offsets. Sure, it’s affecting the results.

**Comment by Xiaohua-Eric-Xu** [comment]
The comparison is made over all data and a subset of that data (I assume this is what @JPPereira93 's doing). Running detrending on interferograms won't explain the differences. If you "moves average value to zero excluding 2pi offsets" for both scenario, it may change the time-series, but differences will still exist. It may gets smaller but that's because of the removal of the trend, which may cover up the actual cause of such differences.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu I suppose we see here smothered 2pi differences due to not detrended unwrapping and so similar differences could be even between the same repeated calculations. Anyway, we need to control unwrapping stability using different resolution unwrapping to be sure. Also, average value and standard deviation per interferogram plots are informative as I’ve referenced above. Unfortunately, GMTSAR makes all the quality check extremely difficult and so lots of users ignore them completely.

**Comment by SteffanDavies** [comment]
> @Xiaohua-Eric-Xu I suppose we see here smothered 2pi differences due to not detrended unwrapping and so similar differences could be even between the same repeated calculations. Anyway, we need to control unwrapping stability using different resolution unwrapping to be sure. Also, average value and standard deviation per interferogram plots are informative as I’ve referenced above. Unfortunately, GMTSAR makes all the quality check extremely difficult and so lots of users ignore them completely.

From what I understand the products used in both of these datasets where detrended with -N3r after unwrapping.

**Comment by mobigroup** [comment]
That’s obviously not enough when we have a separately unwrapped areas with different 2piN offsets. Forgot GMT tools and use Gaussian filter for spare data. The Python realization available in PyGMTSAR code here: https://github.com/mobigroup/gmtsar/blob/pygmtsar/pygmtsar/pygmtsar/SBAS_detrend.py
