### ISSUE TITLE
[Feature]: grdcut

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#686]
hi,dear professors,
command:gmt grdcut corr.grd -Rmask_def_cut.grd -G11.grd
1. Mask_def_cut-grd is a mask file (irregular shape) that I created.
xmin/xmax/ymin/ymax=416/65088/-64/9088
2. corr.grd: xmin/xmax/ymin/ymax=0/68496/0/13064
3, 11.grd is obtained from the grdcut command, xmin/xmax/ymin/ymax=416/65088/0/9088
![`X%6LB_Z@PUZCW9NZ%}KBVU](https://user-images.githubusercontent.com/114629377/224478311-37ae6c4a-5cca-4b21-ac17-10056dd80191.png)
![DQ_9)}QEL%PF_OF(SOPD%9Y](https://user-images.githubusercontent.com/114629377/224478330-d4f7b176-a86a-4d8b-a559-d60a66d9da96.png)

However, the size of the clipped 11.grd is different from that of the mask_def_cut.grd, which will cause the subsequent unwrapping failure. And you can't multiply files. grdmath A.grd B.grd MUL = C.grd .What command should I use to get irregular corr.grd? grdmask?

**Comment by Xiaohua-Eric-Xu** [comment]
Are your mask_def_cut.grd using the same increment as corr.grd? Based on their shape in ncview, I assume not. Then when you cut, the boundaries may fall between pixels which will, of course, give you an unexpected size. I would just use `gmt grdsample` over your mask_def_cut.grd rather than modifying corr.grd. If your mask is not large enough then consider making a larger one.

**Comment by Luvina0503** [comment]
ok.thank you .let me try
