### ISSUE TITLE
[Help]: odd stipes in velocity and displacement maps after running sbas

### ISSUE THREAD

**Issue by geodesico** [gmtsar/gmtsar#691]
Running an SBAS processing for a S-1 dataset worked well apparently. But the final outcomes for the velocity and displacement maps included strange stripes which have appeared after running `sbas`:

`sbas intf.tab scene.tab 198 60 3057 3410 -wavelength 0.0554658 -incidence 35 -range 800000 -rms -dem`

A screenshot of the velocity map:
![vel_stripes](https://user-images.githubusercontent.com/122477115/225117267-04beee4a-110b-4cfb-8d71-82e808511d2a.png)

The stripes do not present in the phasefilt and unwrap/unwrap_dtr results.

**Comment by SteffanDavies** [comment]
What is your pixel / grid spacing?

**Comment by geodesico** [comment]
> What is your pixel / grid spacing?

30 m

**Comment by Xiaohua-Eric-Xu** [comment]
Is this before or after geocoding? If it is after geocoding, try a slightly larger wavelength with proj_ra2ll.csh. e.g., 160m

**Comment by geodesico** [comment]
Thanks, Eric!
The larger wavelength with proj_ra2ll.csh (160 m) solved the stripes issue, but what if I want to get a full-resolution geocoding? This will be necessary for locally deformed spots (e.g., small landslides, etc.)

**Comment by Xiaohua-Eric-Xu** [comment]
There is no actual "full-resolution" geocoding if your target is to get a output grid. Creating a grid requires some mosaicing, which means over certain output pixel, you may have one or two or more data points inside. Also, the sampling in range and azimuth may not be a square so that's an issue too. To get higher sampling, you could 1. process the data in full resolution with 60m gaussian filtering, or 2.project the data points rather than creating a grid (with proj_ra2ll_ascii.csh? you may need to modify the script so the solution achieves higher geocoding accuracy).

**Comment by geodesico** [comment]
Could you please give more information on both options? 
How to project the data points?

**Comment by Xiaohua-Eric-Xu** [comment]
2 is a bit complicated and may require that you are very familiar with GMTSAR. Here's how you could do 1. Use 60 for filter_wavelength in the config file, set azimuth_dec = 1 and range_dec to be 1 or 2 or 4, then run the processing and in the end you'll get about 15 m sampling after geocoding. This is probably the best you can do with Sentinel-1 TOPS data. For other satellites, it then depends on the PRF and range sampling rate.

**Comment by SteffanDavies** [comment]
> Thanks! That will help a lot. With this configuration, what should I set the dec_factor?

You can put it at 1 I suppose.

**Comment by geodesico** [comment]
> > Thanks! That will help a lot. With this configuration, what should I set the dec_factor?
> 
> You can put it at 1 I suppose.

Thanks! I'll try this config. Hope the computer can handle this
