### ISSUE TITLE
[Help]: How can I convert dem.grd or topo_ra.grd to hgt.mat that stamps can handle?

### ISSUE THREAD

**Issue by PickleRickrx** [gmtsar/gmtsar#697]
Hi everyone,I wonder know how can I convert dem.grd or topo_ra.grd to hgt.mat that stamps can handle?

**Comment by Xiaohua-Eric-Xu** [comment]
topo_ra.grd is a height map above a single reference radius stored in the corresponding PRM file (master.PRM in topo directory). I guess for StaMPS, the height needs to be above ellipsoid?  There is a script that does grid projection from geocoordinates to radar coordinates called proj_ll2ra.csh. It has some hard-coded resolution parameters though, so in order to get your DEM projected to radar coordinates, you may need to make those parameters smaller (mostly related to -I options in GMT)?

**Comment by PickleRickrx** [comment]
> topo_ra.grd is a height map above a single reference radius stored in the corresponding PRM file (master.PRM in topo directory). I guess for StaMPS, the height needs to be above ellipsoid? There is a script that does grid projection from geocoordinates to radar coordinates called proj_ll2ra.csh. It has some hard-coded resolution parameters though, so in order to get your DEM projected to radar coordinates, you may need to make those parameters smaller (mostly related to -I options in GMT)?
Thank you for your answer, I know proj_ll2ra.csh, but because the hgt.mat of stamps is a column vector, I don’t know how to convert the radar coordinates of dem into the corresponding hgt.mat format, do you have any solution to this problem?
![1679473183432](https://user-images.githubusercontent.com/93982725/226841684-65eb0eb6-754e-403f-a144-e1b5ccd516c1.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
To convert grids to a binary table, use `gmt grd2xyz`. You could select output format, start of and end of the output, etc., with options like -bo, -Z, etc.

**Comment by PickleRickrx** [comment]
> To convert grids to a binary table, use `gmt grd2xyz`. You could select output format, start of and end of the output, etc., with options like -bo, -Z, etc.

Thank you for youre reply, it has been solved!
