### ISSUE TITLE
SBAS result not maksed

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#714]
Hi，Professor
I am followed the manual：https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf in my
AOI.
Everything is doing well，After my sbas command finshed successfully I noticed that my result on water covered area was not masked,Did I missed something？
![QQ截图20230409155742](https://user-images.githubusercontent.com/20898434/230761253-1244d5a1-fd1f-46b1-b803-5d01cf054127.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to create a landmask_ra.grd with landmask.csh before running snaphu[_interp].csh. That is mainly to save processing time as unwrapping over water costs lots of time and give no valid results. But since you have finished unwrapping (not sure how long that took), you could also chose to throw away anything that's inside the wet region. The masking (throwing away data) could be done with applying the landmask_ra.grd to the vel.grd produced by sbas.

**Comment by Yaoshangheng** [comment]
That unwrapping took me a long time.While I found landmask_ra.grd in each of my data1-data2 file. 
![3](https://user-images.githubusercontent.com/20898434/230943778-ae67a9ca-d3b4-4d00-aa1e-441506a22608.jpg)


Maybe It's my 'unwrap_intf.csh' problem？
My unwra.pdf show something inside the wet region.
![5](https://user-images.githubusercontent.com/20898434/230944488-71faa3b1-b9a7-4059-bf40-46fb7963a6be.jpg)



![4](https://user-images.githubusercontent.com/20898434/230943811-014dcc30-a3c0-4a31-85d8-1872a9e02a4c.jpg)
Which of the command should I use ‘ln -s ../landmask_ra.grd . ‘ or ‘ln -s ../mask.grd .’ ？

**Comment by Xiaohua-Eric-Xu** [comment]
If you run a `gmt grdinfo landmask_ra.grd`, does the bounds match your phasefilt.grd? Could be a bug in the code.

**Comment by Yaoshangheng** [comment]
> If you run a `gmt grdinfo landmask_ra.grd`, does the bounds match your phasefilt.grd? Could be a bug in the code.

I have found the problem，I haven't created a landmask_ra.grd with landmask.csh before running snaphu，I will do it again and re-unwrapping.Thanks for you reply.

Have a good day!
