### ISSUE TITLE
[Help]: something wrong about proj_ra2ll.csh trans.dat vel.grd vel_ll.grd

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#737]
is it about low corrence or something wrong about steps before

![1684159744400](https://github.com/gmtsar/gmtsar/assets/111356557/3f8ebc40-12b4-460c-9fda-f02fc8b814a3)

**Comment by Xiaohua-Eric-Xu** [comment]
I don't see any error on this screenshot. Not sure what is wrong with proj_ra2ll.csh.

**Comment by jerry7nol** [comment]
> I don't see any error on this screenshot. Not sure what is wrong with proj_ra2ll.csh.

![1684374172444](https://github.com/gmtsar/gmtsar/assets/111356557/4d1fe6d6-23f1-41b1-b520-209322bdb7cf)
this is result of sbas mine, look not good,so it's just about low corrence?

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like loss of pixels due to masking out too much during phase unwrapping. It is recommended to create a common coherence mask with `stack_coherence_mask.csh` and then when doing phase unwrapping use a very small coherence threshold (e.g. 0.001), so pixels will be masked with average coherence rather than randomly thrown away by snaphu.csh.

**Comment by jerry7nol** [comment]
> Looks like loss of pixels due to masking out too much during phase unwrapping. It is recommended to create a common coherence mask with and then when doing phase unwrapping use a very small coherence threshold (e.g. 0.001), so pixels will be masked with average coherence rather than randomly thrown away by snaphu.csh`stack_coherence_mask.csh`.

thank you sir
