### ISSUE TITLE
[Help]: GMTSAR image decimation

### ISSUE THREAD

**Issue by bjmarfito** [gmtsar/gmtsar#79]
Do the range and azimuth image decimation of GMTSAR is same as the range and azimuth multilook of ISCE?

**Comment by Xiaohua-Eric-Xu** [comment]
Nope. Multi-look is a boxcar filter with decimation equals filter size. In GMTSAR, decimation will determine the down-sampling of the data. At the sampling position, filter-wavelength determines the filter that applies to the data.

**Comment by bjmarfito** [comment]
Thank you Eric for your response. Would you explain  more in-depth the process of decimating the images or give me references regarding this? I am planning to create a code to ingest GMTSAR stack interferograms results to MintPy.

**Comment by dsandwell** [comment]
Hi Brian,

There is a code in GMT called 

make_gaussian_filter.c

The user selects a desired spatial resolution say 200 m and the code first computes the pixel size (m) in both range an azimuth.  Then it generates a gaussian filter function that will have a 0.5 gain at the desired wavelength.  Finally it computes the decimation to be 1/4 of the desired wavelength.   The range decimattion could be different for each of the three subswaths of Sentinel-1 because the ground-range pixel size varies.  So for merging sub swaths the user can specify the decimation so they all match.

Codes such as ISCE use a boxcar filter followed by decimation.  This is called multi looking.  

Here is a link to some slides that describe these two filters.  We should add this to the GMTSAR documentation.

https://drive.google.com/file/d/1wgfn0ITotaKHBfVvHsOUMwOn06exKtsO/view?usp=sharing

David


 // compute the range and azimuth pixel size
        azi_px_size = prm.vel / sqrt(1 + prm.ht / prm.RE) / prm.prf; // real_vel/prf
        rng_px_size = c_speed / prm.fs / 2;

        // compute the cosine of the looking angle and the surface deviate angle
        a = prm.ht + prm.RE;
        prm.far_range = prm.near_range + rng_px_size * (double)prm.num_rng_bins;
        rng = (prm.near_range + prm.far_range) / 2;
        cost = (pow(a, 2.0) + pow(rng, 2.0) - pow(prm.RE, 2.0)) / 2 / a / rng;
        cosa = (pow(a, 2.0) + pow(prm.RE, 2.0) - pow(rng, 2.0)) / 2 / a / prm.RE;
        // fprintf(stderr,"cosa = %.9f, cost = %.9f\n", cosa ,cost);

        // compute the ground range pixel size
        rng_px_size = rng_px_size / sin(acos(cost) + acos(cosa));

        azi_px_size = azi_px_size * azi_dec;
        rng_px_size = rng_px_size * rng_dec;

        sig_azi = w / 5.3 / azi_px_size;
        sig_rng = w / 5.3 / rng_px_size;
        idec = floor(sig_azi / 2.);
        if (idec < 1)
                idec = 1;
        jdec = floor(sig_rng / 2.);
        if (jdec < 1)
                jdec = 1;
        fprintf(stdout, " %d %d \n", idec, jdec);

        n_azi = (int)(sig_azi * 4);
        n_rng = (int)(sig_rng * 4);

        if (n_azi % 2 == 0)
                n_azi = n_azi + 1;
        if (n_rng % 2 == 0)
                n_rng = n_rng + 1;



> On Jan 6, 2021, at 12:19 AM, Bryan Marfito <notifications@github.com> wrote:
> 
> 
> Thank you Eric for your response. Would you explain more in-depth the process of decimating the images or give me references regarding this? I am planning to create a code to ingest GMTSAR stack interferograms results to MintPy.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by bjmarfito** [comment]
Thank you David for this information. It helped me grasp the difference between the two.
