### ISSUE TITLE
[Help]: Processing single subswath of Sentinel-1 time series

### ISSUE THREAD

**Issue by peolsen1** [gmtsar/gmtsar#810]
First off let me thank you for maintaining such a great repository and for constantly responding quickly to questions from the public.  I am trying to speed up the processing by running smaller regions and only processing a single subswath when it covers my region of interest.

**Processing single subswath**

GMTSAR and works wonderfully when I process 2 or 3 subswaths, but when I try to process a single subswath to save on compute and disk space it isn't obvious how to do it.  

Here's what I tried to get it to work

1) I generated landmask_ra.grd by utilizing the topo_ra.grd in the F2/topo directory (I ran the program in the topo directory).  (For my region of interest there is no ocean, so the landmask is uniform.)

2) I ran the unwrapping directly exactly as in the sentinel_time_series_5.pdf document, except I ran it in the F2 directory.

3) For the sbas program I had no supermaster.PRM in any of the directories F2/intf_all/date1_date2/, so I went to the raw directory for the master date (/F2/raw/S1_20230503_ALL_F2.PRM) and got the parameters from there.

All the code runs fine, but I wonder if my assumptions are correct, and if I have made some mistakes.  Also, I worry about not having any supermaster.PRM files as this will be a problem when I try to do the GNSS correction.

Incidentally, I checked out issue #681 but the comments there didn't seem to help me.  p2p_process appears to generate interferograms which I already have.

Here is the directory listing for one of the interferogram directories:

> > ls intf_all/2023122_2023146
S1_20230503_ALL_F2.LED  S1_20230527_ALL_F2.SLC  corr.cpt         display_amp.pdf  ijdec                  mask2_patch.grd  phasefilt.pdf         unwrap.cpt
S1_20230503_ALL_F2.PRM  amp.grd                 corr.grd         filtcorr.grd     imagfilt.grd           phase.cpt        phasefilt_interp.grd  unwrap.grd
S1_20230503_ALL_F2.SLC  amp1.grd                corr.pdf         gauss_200        landmask_ra.grd        phase.grd        realfilt.grd          unwrap.pdf
S1_20230527_ALL_F2.LED  amp2.grd                display_amp.cpt  gmt.conf         landmask_ra_patch.grd  phase.pdf        snaphu.conf.brief
S1_20230527_ALL_F2.PRM  conncomp.grd            display_amp.grd  gmt.history      mask.grd               phasefilt.grd    topo_ra.grd

- Peder

**Comment by peolsen1** [comment]
I particularly worry about the supermaster.PRM file because there is an rshift parameter that differs for each interferogram pair when I run the code with subswath merging as in the document, and I don't have any supermaster.PRM files at the end of my processing.

**Comment by Xiaohua-Eric-Xu** [comment]
You are absolutely correct here. The merged produce needs a supermaster.PRM mainly because the start time and near range has to change after combing data from several subswaths. For a single subswath, it is not a requirement at all. 

The rshift parameter inside the supermaster.PRM is sued to refer to the coordinates change of the reference image (from the master image). It is used during the merging process and is not a deal for single subswath processing.

**Comment by peolsen1** [comment]
> You are absolutely correct here. The merged produce needs a supermaster.PRM mainly because the start time and near range has to change after combing data from several subswaths. For a single subswath, it is not a requirement at all.
> 
> The rshift parameter inside the supermaster.PRM is sued to refer to the coordinates change of the reference image (from the master image). It is used during the merging process and is not a deal for single subswath processing.

Thanks for you reply.  That makes me feel much more confident.  Does that mean that I can use the /F2/raw/S1_20230503_ALL_F2.PRM and create a supermaster.PRM with rshift=0 when doing GNSS correction, or is there a way for me to generate a proper supermaster.PRM and calculate rshift?

**Comment by Xiaohua-Eric-Xu** [comment]
You should be using the supermaster.PRM for GNSS correction. Here are some explanation.
e.g., you coregister data2 and data3 to data1, with different rshift r2 and r3 applied. Then you produce an interferogram between data2 and data3. When you run any geocoding or calculation of coordinates, you should not use the original PRM2, because data2 is already shifted. But with the recorded shift parameters, you are able to calculate it correctly. This is why the shift parameters are different and stored in each PRM files though they are in the same coordinates. Essentially, you could just use the supermaster.PRM file since it is calculated with the master image coordinates (data1).

**Comment by Xiaohua-Eric-Xu** [comment]
The shift parameters should be stored under each F*/raw directories in each S1*ALL*PRM files, named as r_shift, a_shift, a_stretch, r_stretch, etc. Do note they may be different for the same acquisition but different subswaths. You could calculate your own supermaster.PRM. Please refer to the formula in merge_swath.c.

**Comment by peolsen1** [comment]
This is awesome, thank you so much for the explanation.
