### ISSUE TITLE
[Bug]: Stitching offset in merge_swath.c

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#819]
To test the accuracy of merge_swath.c, I used it to stitch subswaths before interferogram processing. I found that it produces an offset, specifically a 1-pixel azimuthal offset in this case. You can see the resulting plot below:

![intfER](https://github.com/gmtsar/gmtsar/assets/7342379/0520a590-3c75-4efc-8295-adb612244c1a)

In the case of accurate processing, it would be possible to process the stitched images as shown below, where the offset is fixed:

![intfOK](https://github.com/gmtsar/gmtsar/assets/7342379/24e7bf5c-3e57-4e31-91e9-156c22f7bdd1)

I understand that GMTSAR supposes stitching after interferogram processing, but the offset still exists, and although it's hard to detect, it produces inaccurate results. This test merely emphasizes the problem.

**Comment by Xiaohua-Eric-Xu** [comment]
This is a really interesting post. We switched to subswaths processing from full frame processing mainly because of the issue above (regardless of the memory cost, etc.). At the beginning, I thought the time calculation should be accurate enough since the orbit error should be around a few centimeters accuracy. But when I put all SLC products together sometimes the one-line (or two lines sometimes) offset happens just as above. 

I was not able to figure out exactly why, and feels to me that the rounding of calculation sometimes will just get you to different lines, especially when the two images used for interferometry are both aligned images. I kind of suspected whether it is due to the shift/stretch parameters being not accurately stored, but seems the precision was OK. I also suspected whether it is due to that I did not take care of the shift in the aligned images (in other words, one should use merge_batch.csh instead of directly using merge_swath.c, merge_batch.csh was written later BTW). But since the process and stitch approach was already working, I did not continue the other direction. 

Maybe this is a good time to test it out:
1) run pre_proc_batch_tops.csh to coregister the two images.
2) use merge_batch.csh to stitch the SLCs together. (it considers the shift parameters)
3) process the interferogram.

**Comment by mobigroup** [comment]
This is not a rounding issue; I've thoroughly checked it, and the offset before rounding typically appears as 1.0001 or 0.9998. I conducted several tests, yet I still don't fully understand the reason behind this offset. In principle, we could utilize the reference grid stitching parameters and the first subswath repeat image rshift.

Regarding processing performance, Sentinel-1 topography correction and phase difference calculations are well parallelized. In addition, we have the capability to compute only a patch instead of the full interferogram, which is defined by the landmask, for example. On an 8-core Apple Silicon Air laptop, calculating a full scene interferogram (including 3 subswaths and all bursts) takes approximately 40 seconds, whereas GMTSAR phasediff requires over 3 minutes. Furthermore, the patch below can be computed in just 15 seconds. Of course, it simplifies the processing significantly when we no longer need to concern ourselves with separate subswaths. As a major bonus, we can be confident that the stitching is always accurate when the interferogram is well-formed. At the end of the day, we can even perform the processing on the fly, which is a crucial step in achieving complete diskless Sentinel-1 data processing. 

![image](https://github.com/gmtsar/gmtsar/assets/7342379/c91b59a4-1d22-4ae3-b6c9-06232cdfcd43)

![image](https://github.com/gmtsar/gmtsar/assets/7342379/903053ba-b24d-47ba-842d-f8e39086ee6d)

**Comment by mobigroup** [comment]
P.S. We can also avoid concerns about radar topography spacing and NaN values by employing accurate (cubic) topography interpolation on the complete radar coordinates grid.

**Comment by Xiaohua-Eric-Xu** [comment]
> This is not a rounding issue; I've thoroughly checked it, and the offset before rounding typically appears as 1.0001 or 0.9998. I conducted several tests, yet I still don't fully understand the reason behind this offset. In principle, we could utilize the reference grid stitching parameters and the first subswath repeat image rshift.

Did you succeed merging before running interferometry? 

Another issue specifically for TOPS data is that one could not directly sample the SLC data due to existence of ramp introduced by antenna steering. If it is like other ScanSAR data, it should be easier for any code changes.

**Comment by Xiaohua-Eric-Xu** [comment]
> In addition, we have the capability to compute only a patch instead of the full interferogram, which is defined by the landmask, for example. On an 8-core Apple Silicon Air laptop, calculating a full scene interferogram (including 3 subswaths and all bursts) takes approximately 40 seconds,

This can be done by pre-organizing the data by extracting that specific burst for processing I believe.

**Comment by mobigroup** [comment]
> This can be done by pre-organizing the data by extracting that specific burst for processing I believe.

When we extract only some bursts, the parallel processing time is just a few seconds and still about 10 times faster on 8 cores Apple Air than what GMTSAR allows. On a modern 64- or 128-core host, the difference can be as much as 100 times faster!

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu You can find some interactive online examples for merged subswath processing on Google Colab: https://github.com/mobigroup/gmtsar. By the way, this approach simplifies the cropping of small areas intersecting different bursts.
