### ISSUE TITLE
[Help]: Connection two differently processed datasets

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#856]
Hie Eric 
Hope you are doing well.

I was curious if we could process for example 2017 to 2021 of an area and after some months process the same area with same frame and path  for year 2022. so now if we have two different batches of disp.grd files in two different SBAS folder.
Will it be fine if we combine the two datasets to form a continuous time series and velocity from 2017 to 2023.
If yes then how.
So how we cut the disp.grd of different batches to same radar coordinates to form a continuous time series and velcoity from 2017 to 2023.

**Comment by mobigroup** [comment]
You can process all your scenes together without any gaps. Technically, it's possible to add a zero interferogram to cover the missed dates for a consistent SBAS analysis. Additionally, there's the option to align all the scenes and conduct SBAS analysis twice for the two subsets. This approach would produce two series of displacements in the same radar coordinates. Also, your results can be merged in geographic coordinates.

**Comment by Xiaohua-Eric-Xu** [comment]
@shivamthescienceguy , I understand that sometimes one don't want to re-solve a whole new time-series and re-do the analysis, since it is just too much trouble to start over. They may cover slightly different area, sampling choices are different, etc. However, I have to say the time-series solution is a global solution which means former time epochs may affect later ones, unless you solved your time-series with tracking approach such as Kalman filtering. 

If you really don't want to start over, I then recommend to combine them with your modeling. e.g., you want to solve for volume change of a revisor, then leave the time-series but rather solve for a continuous model instead. It might be easier this way.
