### ISSUE TITLE
[Help]: PRM file question

### ISSUE THREAD

**Issue by dcl-grow** [gmtsar/gmtsar#874]
Hi Professor

The workflow of gmtsar is to interfere with each swath first, and then merge the results of each swath. 
Before merging, there will be two PRM files corresponding to each date image. But there is only one supermaster.PRM file in the  merge/* .  Because the files that GMTSAR should provide in the file structure of MintPy are shown in the following figure, but I am not sure about the two PRM files and the corresponding LED files. If the PRM file cannot be determined, the baselin.txt file cannot be calculated correctly.

So what can I do to get the correct merged PRM and LED files corresponding to each dates image?
Thank you very much

![1705669332710](https://github.com/gmtsar/gmtsar/assets/54585193/4e90a3a6-6363-4e2d-ab68-13e724e083a4)

**Comment by mobigroup** [comment]
You can use interactive PyGMTSAR (Python InSAR) to prevent such problems: https://github.com/mobigroup/gmtsar

**Comment by Xiaohua-Eric-Xu** [comment]
So you are trying to get the results into MintPy I think. I think there is a script in MintPy to convert info from GMTSAR into inputs for the software. For your questions
supermaster.PRM is computed for the master image only as that is the reference radar coordinates after coregistration. For baseline computation purpose, you could use results from subswath one, as it should be computing based on the full baseline info rather than just perpendicular or parallel baseline that are dependent on range.

**Comment by Xiaohua-Eric-Xu** [comment]
> You can use interactive PyGMTSAR (Python InSAR) to prevent such problems: https://github.com/mobigroup/gmtsar

I understand that you get a nice processing chain built and would like more folks to try it out, but the purpose for this issue pages / forum is to help users address problems they meet using GMTSAR. It is recommended to provide your solution to the problem rather than constantly leaving a link for another package, which I personally think is not very polite either to the developers or to the users.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu, it appears that GMTSAR is not well-supported at the moment, with many tickets remaining unanswered for a week or more. I believe suggesting PyGMTSAR, which effectively resolves all the reported issues, is a suitable approach and certainly better than no response at all. If you find this inappropriate for any reason, I can refrain from visiting the tickets, though it seems you and I are the only ones still responding here. Perhaps you could consider building and integrating an AI GMTSAR assistant, as I suggested in another ticket. Or has the GMTSAR project completely died, and you are waiting for no more tickets to be opened? We understand you're busy with your new position.

**Comment by Xiaohua-Eric-Xu** [comment]
Indeed I am a bit over-occupied at the moment, but the development is going, though I haven't been paid to do so for a long time now. 

As you may or maynot know, this is not the only place where I get GMTSAR related questions. Emails, chat-groups, etc. Suggesting another software is totally fine as is done by others such as AwesomeSAR (https://github.com/RadarCODE/awesome-sar) and we do love exchanging on ideas though due to limited time some of them cannot be achieved in a relatively short time frame. What I feel inappropriate, however, is repeating a single line link and calling that an answer. Take this ticket for example, the user is trying to get GMTSAR processed interferograms into MintPy (https://github.com/insarlab/MintPy), which is a software specifically written for time-series analysis with lots of functions to correct artifacts like atmosphere, plate motion, tides, etc. An expected answer should be to help the user find a way to do that rather than just posting a link. 

Seems from your definition, that can be considered as an answer, so please refrain from visiting the tickets.

**Comment by AlexeyPechnikov** [comment]
> Indeed I am a bit over-occupied at the moment, but the development is going...

Great to know! By the way, some updates on the GitHub main page would be valuable to track progress. Currently, the long-standing broken CI tests and questions that have been unanswered for weeks give a sense of stagnation.

> Take this ticket for example, the user is trying to get GMTSAR processed interferograms into MintPy (https://github.com/insarlab/MintPy), which is a software specifically written for time-series analysis with lots of functions to correct artifacts like atmosphere, plate motion, tides, etc. 

Perhaps you overlooked that PyGMTSAR already offers all the listed capabilities and more, even online on Google Colab. The best approach is to visit the GitHub page for interactive live examples or consult the PyGMTSAR AI assistant for precise guidance.

> Seems from your definition, that can be considered as an answer, so please refrain from visiting the tickets.

Ok, I understand. Thank you for your efforts in developing the project and providing support!

**Comment by dcl-grow** [comment]
> So you are trying to get the results into MintPy I think. I think there is a script in MintPy to convert info from GMTSAR into inputs for the software. For your questions supermaster.PRM is computed for the master image only as that is the reference radar coordinates after coregistration. For baseline computation purpose, you could use results from subswath one, as it should be computing based on the full baseline info rather than just perpendicular or parallel baseline that are dependent on range.

Sorry for the late reply. Thank you very much for your answer. I think I already know the solution.
