### ISSUE TITLE
[Help]: Installation on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ericlindsey** [gmtsar/gmtsar#936]
I am attempting to install GMTSAR (branch 6.5 or 6.4 both give the same errors) on my Ubuntu 22.04 machine. Previously I was able to install GMTSAR (about a year ago) just fine, and I still have all the libraries installed, following the Wiki instructions.

However, now I get a bunch of errors like this:

`/usr/bin/ld: /home/software/GMTSAR2/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): multiple definition of 'debug'; bperp.o:(.bss+0x30): first defined here`
`/usr/bin/ld: /home/software/GMTSAR2/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): multiple definition of 'SAR_mode'; bperp.o:(.bss+0x0): first defined here`
`/usr/bin/ld: /home/software/GMTSAR2/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): multiple definition of 'forced_slope'; bperp.o:(.bss+0x8): first defined here`
...
`collect2: error: ld returned 1 exit status`
`make[1]: *** [Makefile:71: bperp] Error 1`

This happens for essentially all the compile steps that include 'libgmtsar.a', so I think something went wrong earlier, though there weren't any errors for that step. I'm not sure how to troubleshoot this however.

**Comment by Xiaohua-Eric-Xu** [comment]
The problem comes from an earlier notified issue starting with Ubuntu 21.04. The c complier doesn't like that we sometimes re-define a function that shares the same name as in the library. By adding `-z muldefs` to your `CFLAGS` and `LDFLAGS` will solve the problem. 

A better solution is clearly re-name all the functions that have multiple definition. Hopefully I can get some time to work on this latter in the summer.

**Comment by ericlindsey** [comment]
Aha, I remember seeing that before. Thanks, this worked perfectly!

**Comment by ericlindsey** [comment]
Aha, I remember seeing that before. Thanks, this worked perfectly!
