### ISSUE TITLE
[Help]: How to solve killed problem when doing the land mask?

### ISSUE THREAD

**Issue by xsjjjjj** [gmtsar/gmtsar#961]
I am doing the time series following sentinel_time_series_6.pdf
and I am doing 8.unwrapping interferograms : using landmark.csh to mask out the wet areas
but when I run "landmask.csh minX/maxX/minY/maxY" there seems to have a problem
![Screenshot from 2024-07-23 17-14-04](https://github.com/user-attachments/assets/eb564fce-25ac-4f9b-92b1-1937f780c82d)

![Screenshot from 2024-07-23 17-21-16](https://github.com/user-attachments/assets/d0b90823-d257-4860-9d07-f579b281649a)

**Comment by xsjjjjj** [comment]
the parameters I use are all default parameters btw

**Comment by Xiaohua-Eric-Xu** [comment]
The `Killed` term on your terminal may indicate a lack of RAM.

**Comment by arashfathollahi** [comment]
Hello and good day,

I am encountering a "cannot find file landmask_ra.grd" error while processing the interferogram. Below are my system specifications:

GMTSAR 6.5
GMT 6.3
Ubuntu 22.04
ASUS: CPU = AMD R7 6800H, RAM = 16 GB DDR5, GPU = RTX 3070
The issue arises specifically when I set the mask value to 1 in the batch_tops.config file to mask the wet regions. Interestingly, if I set the value to "no" so that masking does not occur, no error appears.
All steps run correctly except for the landmask section.
I would appreciate any guidance you can provide. Thank you!
![Screenshot from 2024-08-30 23-47-01](https://github.com/user-attachments/assets/2113fd6f-6047-4c0f-88a7-0e141e9656c8)
![Screenshot from 2024-09-02 05-53-14](https://github.com/user-attachments/assets/dd64450f-b327-401b-8e73-aad31fd8a1e3)
